# Basic App Configuration
name: classrecord-api         # App name in DigitalOcean
region: sfo3                  # Preferred region (sfo3 is San Francisco)
services:
  - name: backend             # Your Spring Boot service
    github:
      branch: master          # Auto-deploy on pushes to main
      deploy_on_push: true    # Enable CI/CD
    source_dir: /             # Root directory of your repo

    # Build & Runtime
    dockerfile_path: Dockerfile  # Uses Docker for reliable builds (recommended)
    # Alternative if not using Docker:
    # build_command: ./mvnw clean package -DskipTests
    # run_command: java -jar target/ClassRecord-*.jar

    # Resource Allocation
    instance_size_slug: basic-xxs  # Cheapest tier ($5/month)
    instance_count: 1              # Single instance
    http_port: 8080                # Spring Boot's default port

    # Environment Variables
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod               # Activates production profile
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m  # JVM memory limits
      - key: DATABASE_URL
        scope: RUN_TIME           # Injected at runtime
        value: ${db.DATABASE_URL} # Linked to database below

    # Health Checks (Critical for production)
    health_check:
      http_path: /actuator/health  # Spring Boot Actuator endpoint
      port: 8080
      initial_delay_seconds: 30
      period_seconds: 10

# Database Configuration (MariaDB)
databases:
  - name: db
    engine: MARIADB
    version: "10.11"             # Matches your pom.xml
    production: false            # Set to true for prod
    instance_size_slug: db-s-dev-database  # $15/month dev DB
    instance_count: 1