name: classrecord-api
region: sfo3
services:
  - name: backend
    github:
      branch: master
      deploy_on_push: true
    source_dir: /
    dockerfile_path: Dockerfile  # Use Docker for reliability
    
    # Resource settings
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    
    # Environment variables
    envs:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET  # Mark as sensitive
        value: ${db.DATABASE_URL}
    
    # Health check (requires actuator)
    health_check:
      http_path: /actuator/health
      port: 8080
      initial_delay_seconds: 60  # Increased for Spring Boot startup
      period_seconds: 15

databases:
  - name: db
    engine: MARIADB
    version: "10.11"
    production: false
    instance_size_slug: db-s-dev-database